### ISSUE TITLE
acceptOnFirstVisit: true 

### ISSUE THREAD

**Issue by ebisbe** [dobarkod/cookie-banner#56]
acceptOnFirstVisit: true is not working for me. I'm using this implementation:

```
var options = {
    message: Locales[Laravel.language].layout.cookies.message,
    moreinfo: Locales[Laravel.language].layout.cookies.moreinfo,
    linkmsg: Locales[Laravel.language].layout.cookies.linkmsg,
    acceptOnFirstVisit: true
};
var cb = new Cookiebanner(options); cb.run();
```

How I can achieve that behavour??

**Comment by ebisbe** [comment]
I've found that the npm package is not the same.

**Comment by zytzagoo** [comment]
Yeah, looks like the npm package is from this fork: https://github.com/nephila/cookie-banner

**Comment by ebisbe** [comment]
yes and it's not updated any more. I've installed directly throught github url. But a npm package would be awesome

**Comment by zytzagoo** [comment]
It's doable, for sure, but:
* the cookiebanner npm package name is already taken (and is not 1/1 compatible even if we could get back the package name by some miracle -- I think we'd have to do a major version bump at the very least + support older versions for existing users?)
* publishing on npm under a different package name seems to me like it would only introduce even more confusion?

At least that's how it looks to me from the outside, since I'm not deeply intimate with the npm ecosystem... Would love to hear some more thoughts from others on this!
