### ISSUE TITLE
Two links in the message possibility

### ISSUE THREAD

**Issue by fourroses666** [dobarkod/cookie-banner#78]
I need two links, tried it like you can see here below but that doesn't work. Any idea how to fix this?

```
data-message="We use cookies ... and our <a href'/privacy'>privacy statement</a> and "
data-linkmsg="cookiestatement"
data-moreinfo="/cookies"
data-moreinfo-target="_parent">
```

**Comment by zytzagoo** [comment]
The first `a` element inside message will be linked to `moreinfo`, rest is untouched and will be left as-is if provided inside `data-message`:
https://github.com/dobarkod/cookie-banner/blob/ae1a32bfad4143fdfd66782d0150401e50a9b3d9/src/cookiebanner.js#L500

And you'd have to set `data-linkmsg=""` in order to not have the default link shown.

So, as a kind of a workaround, this might give you what you want, if I understood correctly: https://codepen.io/anon/pen/jKraxB

If not, please clarify what exactly you wanted to achieve. Hopefully the pen above helps either way.

**Comment by fourroses666** [comment]
Thank you!
